### PR TITLE
.NET Framework 4.6 

### PR DESCRIPTION
**Pull request by smad2005**

### CODE REVIEW

**Comment by ghost** [comment]
Hi, 
You forgot to add an option for minimap icons for MonsterModsAlerts, ...Reflect, Corrupted ...:)

**Comment by smad2005** [comment]
I will add it later

**Comment by smad2005** [comment]
parser
I'm a little busy with this)

**Comment by ghost** [comment]
Oh, ItemFilter parser :)
Awesome, i'm willing to test it :)
Super nice job,

**Pull request merged**
