### PR TITLE
bigger debuff icon

### PR DESCRIPTION
**Pull request by therock182**

### CODE REVIEW

**Comment by H4vC** [comment]
Is this really needed ?
I mean it seemed okay sized for me but perhaps it's not big enough ? Idk I'm not great with graphics.

**Comment by therock182** [comment]
i set this to 100 in the settings,json, for me is that better.
but the settings.json is created automaticly at the first start? and then it is reset to max 40.
and it is only a better range to chose fromfor the user.

**Comment by H4vC** [comment]
I'll merge it up since it's a minor value change.

**Comment by therock182** [comment]
i dont know where my failure is, but the setting.json has still max 40 for the debufficon when it is created by the .exe

**Comment by H4vC** [comment]
did you recompile ?

**Comment by therock182** [comment]
recompile? sry i dont know what this is for? i just downloaded the updated version and start it the first to time to create a new settings.json.

**Comment by H4vC** [comment]
if you make a change to a program you need to compile it for the changes to take effect I'm not at home so I can't do it and push the executable right now.

**Comment by therock182** [comment]
ok, i thought the programm uses the scripts, but know i understand how it works ^^.
thf for your patience,i will wait for the recompiled exe.
which programm is usefull in windows for doing that?

**Comment by H4vC** [comment]
visual studio

**Pull request merged**
